# Generated by Django 3.1.12 on 2022-01-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(db_index=True, max_length=64)),
                ('time', models.DateField()),
                ('parameter', models.CharField(db_index=True, max_length=64)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(db_index=True, max_length=64)),
                ('time', models.DateField()),
                ('parameter', models.CharField(db_index=True, max_length=64)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(db_index=True, max_length=64)),
                ('time', models.DateField()),
                ('parameter', models.CharField(db_index=True, max_length=64)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
